const foods = [
    { "Nama Makanan": "Sate padang", "Kalori": 161, "Berat": "100 gr" },
    { "Nama Makanan": "Sate kambing", "Kalori": 216, "Berat": "100 gr" },
    { "Nama Makanan": "Daging kelinci", "Kalori": 136, "Berat": "100 gr" },
    { "Nama Makanan": "Ketupat", "Kalori": 160, "Berat": "100 gr" },
    { "Nama Makanan": "Sambal terasi", "Kalori": 15, "Berat": "1 takaran saji (8gr)" },
    { "Nama Makanan": "Sambal bawang", "Kalori": 25, "Berat": "1 sachet (8gr)" },
    { "Nama Makanan": "Laksa", "Kalori": 370, "Berat": "1 porsi (85 gr)" },
    { "Nama Makanan": "Rendang", "Kalori": 195, "Berat": "100 gr" },
    { "Nama Makanan": "Soto ayam", "Kalori": 312, "Berat": "1 mangkok" },
    { "Nama Makanan": "Soto daging", "Kalori": 219, "Berat": "1 mangkok" },
    { "Nama Makanan": "Ayam Serundeng", "Kalori": 260, "Berat": "100 gr" },
    { "Nama Makanan": "Acar", "Kalori": 12, "Berat": "1 sedang" },
    { "Nama Makanan": "Tempe", "Kalori": 193, "Berat": "100 gr" },
    { "Nama Makanan": "Nasi goreng", "Kalori": 333, "Berat": "1 mangkok" },
    { "Nama Makanan": "bakso daging sapi", "Kalori": 57, "Berat": "1 sedang" },
    { "Nama Makanan": "Gado-gado", "Kalori": 132, "Berat": "100 gr" },
    { "Nama Makanan": "Ayam goreng", "Kalori": 260, "Berat": "100 gr" },
    { "Nama Makanan": "Gulai ayam", "Kalori": 202, "Berat": "1 potong" },
    { "Nama Makanan": "Siomay", "Kalori": 51, "Berat": "1 potong" },
    { "Nama Makanan": "Pecel", "Kalori": 79, "Berat": "1 sdm" },
    { "Nama Makanan": "Betutu sambal mata", "Kalori": 490, "Berat": "1 porsi (250 gr)" },
    { "Nama Makanan": "Pempek", "Kalori": 39, "Berat": "1 potong" },
    { "Nama Makanan": "Perkedel", "Kalori": 21, "Berat": "1 potong" },
    { "Nama Makanan": "Nasi kuning", "Kalori": 150, "Berat": "1 mangkok" },
    { "Nama Makanan": "Nasi putih", "Kalori": 204, "Berat": "1 mangkok" },
    { "Nama Makanan": "Bebek goreng", "Kalori": 337, "Berat": "1 potong" },
    { "Nama Makanan": "Bubur ayam", "Kalori": 372, "Berat": "1 porsi" },
    { "Nama Makanan": "Rawon", "Kalori": 119, "Berat": "100 gr" },
    { "Nama Makanan": "Ote ote", "Kalori": 45, "Berat": "1 potong" },
    { "Nama Makanan": "Ayam penyet", "Kalori": 199, "Berat": "100 gr" },
    { "Nama Makanan": "Nasi liwet", "Kalori": 138, "Berat": "100 gr" },
    { "Nama Makanan": "Mie aceh", "Kalori": 116, "Berat": "100 gr" },
    { "Nama Makanan": "Bakso goreng", "Kalori": 57, "Berat": "1 buah" },
    { "Nama Makanan": "Batagor", "Kalori": 290, "Berat": "100 gr" },
    { "Nama Makanan": "Cireng", "Kalori": 70, "Berat": "1 potong" },
    { "Nama Makanan": "Sayur asem", "Kalori": 80, "Berat": "1 mangkok" },
    { "Nama Makanan": "Serabi", "Kalori": 108, "Berat": "1 buah" },
    { "Nama Makanan": "Bakwan", "Kalori": 137, "Berat": "1 potong" },
    { "Nama Makanan": "Pecel lele", "Kalori": 292, "Berat": "1 porsi" },
    { "Nama Makanan": "Rujak", "Kalori": 121, "Berat": "100 gr" },
    { "Nama Makanan": "Ikan panggang", "Kalori": 142, "Berat": "1 irisan" },
    { "Nama Makanan": "Cap cay", "Kalori": 67, "Berat": "100 gr" },
    { "Nama Makanan": "Risoles", "Kalori": 96, "Berat": "1 potong" },
    { "Nama Makanan": "Ayam botok", "Kalori": 229, "Berat": "1 porsi" },
    { "Nama Makanan": "Pisang goreng", "Kalori": 68, "Berat": "1 iris" },
    { "Nama Makanan": "Pisang cokelat", "Kalori": 90, "Berat": "125ml" },
    { "Nama Makanan": "Sayur lodeh", "Kalori": 162, "Berat": "1 mangkok" },
    { "Nama Makanan": "Tengkleng", "Kalori": 350, "Berat": "1 porsi(75gr)" },
    { "Nama Makanan": "Mie glosor", "Kalori": 72, "Berat": "100gr" },
    { "Nama Makanan": "Wajik", "Kalori": 152, "Berat": "1 potong" },
    { "Nama Makanan": "Keripik singkong", "Kalori": 485, "Berat": "100 gr" },
    { "Nama Makanan": "Es teler", "Kalori": 425, "Berat": "1 mangkok" },
    { "Nama Makanan": "Asinan", "Kalori": 148, "Berat": "1 porsi" },
    { "Nama Makanan": "Kerupuk udang", "Kalori": 35, "Berat": "1 sedang" },
    { "Nama Makanan": "Klepon", "Kalori": 110, "Berat": "1 buah" },
    { "Nama Makanan": "Opor ayam", "Kalori": 392, "Berat": "1 porsi" },
    { "Nama Makanan": "Cilok", "Kalori": 266, "Berat": "100 gr" },
    { "Nama Makanan": "Kue lapis", "Kalori": 201, "Berat": "1 potong" },
    { "Nama Makanan": "Lemper ayam ", "Kalori": 133, "Berat": "1 buah" },
    { "Nama Makanan": "Rujak cingur", "Kalori": 249, "Berat": "1 porsi" },
    { "Nama Makanan": "Kue putu ayu", "Kalori": 26, "Berat": "1 buah" },
    { "Nama Makanan": "Tekwan", "Kalori": 224, "Berat": "1 mangkok" },
    { "Nama Makanan": "Tempe mendoan", "Kalori": 200, "Berat": "100 gr" },
    { "Nama Makanan": "Nasi jagung", "Kalori": 150, "Berat": "100 gr" },
    { "Nama Makanan": "Ayam rica rica", "Kalori": 404, "Berat": "1 porsi" },
    { "Nama Makanan": "Dadar gulung", "Kalori": 139, "Berat": "1 potong" },
    { "Nama Makanan": "Getuk", "Kalori": 61, "Berat": "1 potong" },
    { "Nama Makanan": "Kolak", "Kalori": 163, "Berat": "100 gr" },
    { "Nama Makanan": "Tempe goreng", "Kalori": 34, "Berat": "1 buah" },
    { "Nama Makanan": "Tempe orek", "Kalori": 175, "Berat": "100 gr" },
    { "Nama Makanan": "Oncom", "Kalori": 36, "Berat": "100 gr" },
    { "Nama Makanan": "Semur daging", "Kalori": 141, "Berat": "100 gr" },
    { "Nama Makanan": "Ayam geprek", "Kalori": 263, "Berat": "100 gr" },
    { "Nama Makanan": "Otak otak", "Kalori": 189, "Berat": "100 gr" },
    { "Nama Makanan": "Ayam bakar(t.Kulit)", "Kalori": 98, "Berat": "1 potong sedang" },
    { "Nama Makanan": "Bakso ayam", "Kalori": 45, "Berat": "1 sedang" },
    { "Nama Makanan": "Oat", "Kalori": 140, "Berat": "4 Sdm" },
    { "Nama Makanan": "beras merah", "Kalori": 110, "Berat": "100 gr" },
    { "Nama Makanan": "Quinoa", "Kalori": 374, "Berat": "100g" },
    { "Nama Makanan": "Pasta", "Kalori": 220, "Berat": "1 Mangkok" },
    { "Nama Makanan": "Buncis", "Kalori": 31, "Berat": "100 gr" },
    { "Nama Makanan": "Roti tawar", "Kalori": 200, "Berat": "2 lembar(74 gr)" },
    { "Nama Makanan": "Selai", "Kalori": 28, "Berat": "1 tsp (5 gr)" },
    { "Nama Makanan": "Popcorn", "Kalori": 387, "Berat": "100 gr" },
    { "Nama Makanan": "Bulgur", "Kalori": 151, "Berat": "1 mangkok" },
    { "Nama Makanan": "Bayam ", "Kalori": 37, "Berat": "1 mangkok" },
    { "Nama Makanan": "Tepung beras", "Kalori": 365, "Berat": "100 gr" },
    { "Nama Makanan": "Tepung gandum utuh", "Kalori": 407, "Berat": "1 mangkok" },
    { "Nama Makanan": "Tepung terigu", "Kalori": 350, "Berat": "100 gr" },
    { "Nama Makanan": "Ikan salmon", "Kalori": 146, "Berat": "100 gr" },
    { "Nama Makanan": "Ikan Trout panggang", "Kalori": 188, "Berat": "100 gr" },
    { "Nama Makanan": "Kerang", "Kalori": 35, "Berat": "1 kerang" },
    { "Nama Makanan": "Halibut", "Kalori": 223, "Berat": "1/2 irisan" },
    { "Nama Makanan": "Kepiting", "Kalori": 119, "Berat": "1 mangkok" },
    { "Nama Makanan": "Lobster", "Kalori": 114, "Berat": "1 kecil" },
    { "Nama Makanan": "Susu Almond", "Kalori": 40, "Berat": "1 gelas" },
    { "Nama Makanan": "Air Kelapa", "Kalori": 46, "Berat": "1 gelas" },
    { "Nama Makanan": "Beras putih", "Kalori": 361, "Berat": "100 gr" },
    { "Nama Makanan": "Susu kedelai", "Kalori": 54, "Berat": "100 ml" },
    { "Nama Makanan": "Kacang almond", "Kalori": 578, "Berat": "100 gr" },
    { "Nama Makanan": "Kacang tanah", "Kalori": 567, "Berat": "100 gr" },
    { "Nama Makanan": "Kenari", "Kalori": 654, "Berat": "100 gr" },
    { "Nama Makanan": "Kacang mete", "Kalori": 581, "Berat": "100 gr" },
    { "Nama Makanan": "Kacang pinus kering", "Kalori": 673, "Berat": "100 gr" },
    { "Nama Makanan": "Kacang Makadamia", "Kalori": 718, "Berat": "100 gr" },
    { "Nama Makanan": "Selai kacang", "Kalori": 94, "Berat": "1 sdm" },
    { "Nama Makanan": "Biji Rami", "Kalori": 37, "Berat": "1 sdm" },
    { "Nama Makanan": "Mentega", "Kalori": 102, "Berat": "1 sdm" },
    { "Nama Makanan": "Buah zaitun", "Kalori": 5, "Berat": "1 sedang" },
    { "Nama Makanan": "Alpukat", "Kalori": 322, "Berat": "1 alpukat" },
    { "Nama Makanan": "Minyak wijen", "Kalori": 40, "Berat": "1 sdt" },
    { "Nama Makanan": "Mayones ", "Kalori": 57, "Berat": "1 sdm" },
    { "Nama Makanan": "Jus alpukat", "Kalori": 195, "Berat": "1 gelas" },
    { "Nama Makanan": "Yogurt polos", "Kalori": 63, "Berat": "100 gr" },
    { "Nama Makanan": "Buttermilk", "Kalori": 40.4, "Berat": "100 gr" },
    { "Nama Makanan": "Keju cheddar", "Kalori": 403, "Berat": "100 gr" },
    { "Nama Makanan": "Keju Cottage", "Kalori": 103, "Berat": "100 gr" },
    { "Nama Makanan": "Keju krim", "Kalori": 51, "Berat": "1 sdm" },
    { "Nama Makanan": "Telur goreng", "Kalori": 89, "Berat": " 1 besar" },
    { "Nama Makanan": "Telur asin", "Kalori": 137, "Berat": "1 buah" },
    { "Nama Makanan": "Ayam", "Kalori": 17, "Berat": "1 irisan tipis" },
    { "Nama Makanan": "Ikan", "Kalori": 84, "Berat": "100 gr" },
    { "Nama Makanan": "Daging domba", "Kalori": 292, "Berat": "100 gr" },
    { "Nama Makanan": "Babi", "Kalori": 363, "Berat": "1 mangkok" },
    { "Nama Makanan": "Kaldu ayam", "Kalori": 12, "Berat": "1 gelas" },
    { "Nama Makanan": "Sirup", "Kalori": 53, "Berat": "1 sdm" },
    { "Nama Makanan": "Cokelat manis", "Kalori": 505, "Berat": "100 gr" },
    { "Nama Makanan": "Gula pasir", "Kalori": 16, "Berat": "1 sdt" },
    { "Nama Makanan": "Gula merah", "Kalori": 11, "Berat": "1 sdt" },
    { "Nama Makanan": "Kaldu sapi", "Kalori": 7, "Berat": "1 gelas" },
    { "Nama Makanan": "Kaldu jamur", "Kalori": 20, "Berat": "1 sendok (10 gr)" },
    { "Nama Makanan": "Tomat ", "Kalori": 18, "Berat": "100 gr" },
    { "Nama Makanan": "Saus tomat", "Kalori": 15, "Berat": "1 sdm" },
    { "Nama Makanan": "Pasta tomat", "Kalori": 13, "Berat": "1 sdm" },
    { "Nama Makanan": "Saos apel", "Kalori": 86, "Berat": "1 snack ukuran" },
    { "Nama Makanan": "Santan", "Kalori": 230, "Berat": "100 gr" },
    { "Nama Makanan": "Kunyit", "Kalori": 354, "Berat": "100 gr" },
    { "Nama Makanan": "Jahe", "Kalori": 2, "Berat": "1 sdt" },
    { "Nama Makanan": "Labu dimasak", "Kalori": 115, "Berat": "1 mangkok" },
    { "Nama Makanan": "Saos tomat", "Kalori": 15, "Berat": "1 sdm" },
    { "Nama Makanan": "Saos sambal", "Kalori": 20, "Berat": "1 sendok (15gr)" },
    { "Nama Makanan": "Zaitun", "Kalori": 5, "Berat": "1 sedang" },
    { "Nama Makanan": "Lada hitam", "Kalori": 0, "Berat": "1 sejumput" },
    { "Nama Makanan": "Acar", "Kalori": 12, "Berat": "1 sedang" },
    { "Nama Makanan": "Cuka", "Kalori": 3, "Berat": "1 sdm" },
    { "Nama Makanan": "Air ", "Kalori": 0, "Berat": "1 gelas" },
    { "Nama Makanan": "Teh manis", "Kalori": 55, "Berat": "1 gelas" },
    { "Nama Makanan": "Kopi", "Kalori": 2, "Berat": "1 cangkir" }
]
